In [31]:
import pandas as pd

# DIRECT LINK to the Volcanic Eruption dataset — NO file needed!
url = 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv'
volcanoes = pd.read_csv(url)

# Test it works — shows first 5 rows
volcanoes.head()

,volcano_number,volcano_name,eruption_number,eruption_category,area_of_activity,vei,start_year,start_month,start_day,evidence_method_dating,end_year,end_month,end_day,latitude,longitude
0,266030,Soputan,22354,Confirmed Eruption,NaN,NaN,2020.0,3.0,23.0,Historical Observations,2020.0,4.0,2.0,1.112,124.737
1,343100,San Miguel,22355,Confirmed Eruption,NaN,NaN,2020.0,2.0,22.0,Historical Observations,2020.0,2.0,22.0,13.434,-88.269
2,233020,"Fournaise, Piton de la",22343,Confirmed Eruption,NaN,NaN,2020.0,2.0,10.0,Historical Observations,2020.0,4.0,6.0,-21.244,55.708
3,345020,Rincon de la Vieja,22346,Confirmed Eruption,NaN,NaN,2020.0,1.0,31.0,Historical Observations,2020.0,4.0,17.0,10.830,-85.324
4,353010,Fernandina,22347,Confirmed Eruption,NaN,NaN,2020.0,1.0,12.0,Historical Observations,2020.0,1.0,12.0,-0.370,-91.550

Least amount of number of volcanoes

In [32]:
volcanoes['volcano_name'].value_counts(ascending= True).head()

volcano_name
Igwisi Hills                     1
Nantaisan                        1
Black Butte Crater Lava Field    1
Berlin                           1
Damavand                         1
Name: count, dtype: int64

Most amount of numbers of volcanoes

In [33]:
volcanoes['volcano_name'].value_counts(ascending= False).head()

volcano_name
Etna                      241
Fournaise, Piton de la    194
Asosan                    186
Villarrica                164
Asamayama                 147
Name: count, dtype: int64

In [35]:
max_erruption_number = volcanoes['eruption_number'].max()
print('Max eruption number is '+ str(max_erruption_number))

Max eruption number is 22355